[package]
name = "law_mm1"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.7", features = ["derive"] }
csv = "1.3.0"
io = "0.0.2"
rand = "0.8.5"
rand_distr = "0.4.3"
serde = { version = "1.0.203", features = ["derive"] }
serde_derive = "1.0.203"

